# Generated by Django 4.2.7 on 2023-11-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agenda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="next_task_due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agenda",
            name="date",
            field=models.CharField(default="2023-11-11", primary_key=True, serialize=False, unique=True),
        ),
    ]
